### ISSUE TITLE
TODO : Diet planner component

### ISSUE THREAD

**Issue by SubhankarDas** [SubhankarDas/diet-plan-ui#2]
- [ ] Generate ideal diet plan.

- [ ] Add user preferences to diet plan.

- [ ] Perfect diet generation algorithm for more approx values.
